# Introduction to TensorFlow

In [ ]:
!

In [35]:
from __future__ import absolute_import, division, print_function, unicode_literals

In [37]:
# Import all required libraries
import tensorflow as tf
from tensorflow import keras


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tqdm as tqdm
from keras.preprocessing import image
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
 

from six.moves import urllib 
from IPython.display import clear_output
import tensorflow.compat.v2.feature_column as fc 

print(tf.__version__)

2.3.1


## What is Tensorflow?

* It's an open source library developed by google. Basically created for deep learning problem but can also solve traditional machine learning problem
* Developed originally to run large numerical computation
* Accepts data in form of multidimensional arrays of higher dimensions called _Tensors_. They are very handy in handling large amount of data
* Works on the basis of Data Flow graphs that have nodes and edges. Each computation in Tensorflowis represented as a Data Flow Graph
* The Data Flow graph comprise of **Nodes** and **Edges**. Each Node in the graph represents a mathematical operation(add, subtract, multiply etc.) and each edge represents multidimensional arrays(Tensors)
* Data Flow graph enables creating large scale neural networks as computing can be distributed across several CPU's and GPU's

<img src="https://miro.medium.com/max/2994/1*vPb9E0Yd1QUAD0oFmAgaOw.png"/>

## Why Tensorflow?

* It provides both C++ and python API's that makes it easier to work on
* Has faster compilaton time than the other deep learning libraries like Keras and Torch
* Tensorflow supports both CPU's GPU's computing devices

## What are Tensors

Tensor is a generalisation of vecturs and matrices of potentially higher dimension. It keeps the inputted compacted to be inputted into the neural network.

Data is stored in a tensor

### Creating a Tensor

In [15]:
# tf.variable here is used to create a variable(tensor)

string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

print(string, number, floating, sep=" \n\n")

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'> 

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324> 

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567>


### Tensor Ranks

Ranks are dimensions e.g.

* Tensor of rank 0, `s=[200]` has no dimension and is also called a scalar 
* Tensor of rank 1, `v=[10,11,12]` has just one dimension and can be called a vector
* Tensor of rank 2, `m=[[1,2,3],[4,5,6]]` has two dimensions and called a matrix
* Tensor of rank 3, `t=[[[1],[2],[3]],[[4],[5],[6]],[[7],[8],[9]]]` is a 3 dimensional array

It goes on like that. A tensor of rank N is a N-dimensional array

In [22]:

rank1_tensor = tf.Variable(['Test'], tf.string)
rank2_tensor = tf.Variable([['test', 'ok'], ['test', 'yes']], tf.string)


In [23]:
# Determining the rank of variables

rank1 = tf.rank(rank1_tensor)
rank2 = tf.rank(rank2_tensor)

print(rank1, rank2, sep=' \n')

tf.Tensor(1, shape=(), dtype=int32) 
tf.Tensor(2, shape=(), dtype=int32)


### Shapes and Reshaping Tensors

In [25]:
print(rank1_tensor.shape, rank2_tensor.shape, sep='\n')


(1,)
(2, 2)


In [26]:
tensor1 = tf.ones([1,2,3])
tensor1

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [33]:
tensor0 = tf.zeros([5,5,5,5])
tensor0

<tf.Tensor: shape=(5, 5, 5, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

  

In [30]:
# Reshaping the tensor

tensor2 = tf.reshape(tensor1, [2,3,1])
tensor3 = tf.reshape(tensor2, [3,-1])

print(tensor2, tensor3, sep='\n')

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


## Types of Tensors

* Variable
* Constant
* Placeholder
* Sparse Tensor 

### Evaluation of Tensors 

It is required to run a session when we try to evaluate a tensor

## TensorFlow Core Learning Algorithm

* Linear Regression
* Classification
* Clustering
* Hidden Markov Models

## Creating the simplest possible Neural Network

In [3]:
model = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])

Keras is the framework for definig a neural network as a set of sequential layers

In [4]:
model.compile(optimizer='sgd', loss='mean_squared_error')

The loss function passed as argument is used to evaluate the model. While the optimizer keeps tuning the model until loss function is minimized

In [5]:
xs = np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
ys = np.array([-2.0, 1.0, 4.0, 7.0, 10.0, 13.0], dtype=float)

Provide the data for the model as shown above

In [6]:
model.fit(xs, ys, epochs=500)

h 263/500
1/1 [==============================] - 0s 3ms/step - loss: 7.1263e-06
Epoch 264/500
1/1 [==============================] - 0s 3ms/step - loss: 6.9800e-06
Epoch 265/500
1/1 [==============================] - 0s 5ms/step - loss: 6.8369e-06
Epoch 266/500
1/1 [==============================] - 0s 3ms/step - loss: 6.6967e-06
Epoch 267/500
1/1 [==============================] - 0s 2ms/step - loss: 6.5589e-06
Epoch 268/500
1/1 [==============================] - 0s 6ms/step - loss: 6.4241e-06
Epoch 269/500
1/1 [==============================] - 0s 3ms/step - loss: 6.2919e-06
Epoch 270/500
1/1 [==============================] - 0s 3ms/step - loss: 6.1625e-06
Epoch 271/500
1/1 [==============================] - 0s 5ms/step - loss: 6.0358e-06
Epoch 272/500
1/1 [==============================] - 0s 3ms/step - loss: 5.9120e-06
Epoch 273/500
1/1 [==============================] - 0s 5ms/step - loss: 5.7904e-06
Epoch 274/500
1/1 [==============================] - 0s 3ms/step - loss: 5.6715e

Train the model by fitting the data into it

In [7]:
print(model.predict([10.0]))

[[30.999329]]
